Repository PalisadoesFoundation/talawa-api, pull requests merged in 2021-03, with the labels that each got.

#169 Initial draft for contribution guidelines and templates
  CONTRIBUTING.md
  PR-guidelines.md
  issue-guidelines.md
  templates/PR-template.md
  templates/issue-template.md
Labels: documentation

#176 [Bugfix]Update Profile Mutation Creation
  CONTRIBUTING.md
  resolvers/Mutation.js
  resolvers/user_mutations/updateUserProfile.js
  schema/mutation.graphql
  schema/user/user.graphql
Labels: bug, help wanted

#189 [BugFix] Develop branch fix
  resolvers/Mutation.js
Labels: bug
