Repository PalisadoesFoundation/talawa-api, pull requests merged in 2022-03, with the labels that each got.

#610 Upgrade nanoid to 3.1.31
  lib/helper_lib/request-tracing/index.js
  lib/helper_lib/request-tracing/package-lock.json
  lib/helper_lib/request-tracing/package.json
Labels: good first issue

#613 test: Added createOrganization Tests and blockUser Tests
  lib/resolvers/organization_mutations/createOrganization.js
  tests/resolver_tests/organization_mutations/createOrganization.spec.js
Labels: github-externship, test

#648 resolving issue: #554
  lib/resolvers/functions/creatorCheck.js
  lib/resolvers/organization_mutations/removeOrganization.js
  tests/resolvers/organization_mutations/removeOrganization.spec.js
Labels: bug
